### ISSUE TITLE
Feature requests: Disabling Sea and Low poly rendering

### ISSUE THREAD

**Issue by setanarut** [TadaTeruki/fastlem-random-terrain#1]
1. Heightmap without sea.
2. Unrealistic rendering like this image. (Sharp low poly) Zoom option if possible. (zoom to branches)

![Screenshot_2024-02-03-13-16-58-84_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg](https://github.com/TadaTeruki/fastlem-random-terrain/assets/36481442/0e91f5b1-9d58-478c-8644-640152306199)

**Comment by TadaTeruki** [comment]
Thank you. 

> Heightmap without sea.

I will deal with this first.

Actually the water area is always needed to solve the river incision. To create such terrain, you need to set the water area to all edge sites (convex hull) of the terrain data. 

I have added two options: `--land-ratio` and `--convex-hull-is-always-outlet` (see `--help' for details).

To set the `--land-ratio` to 1.0 will remove all oceans from the terrain data. The water area is only for one site (vertex).

```
$ fastlem-random-terrain --colormap-json-filename default_color.json --image-size 300:-1 --land-ratio 1.0
```

![terrain](https://github.com/TadaTeruki/fastlem-random-terrain/assets/69315285/eaea70ac-8509-474b-ba68-bd8c0a29fee2)

To set the `--convex-hull-is-always-outlet`, you can change all edge sites as water area.

```
$ fastlem-random-terrain --colormap-json-filename default_color.json --image-size 300:-1 --land-ratio 1.0 --convex-hull-is-always-outlet
```

![terrain](https://github.com/TadaTeruki/fastlem-random-terrain/assets/69315285/8f7eb5fa-0b90-4407-8979-15acb44a9238)

If necessary, set the `--erodibility-distribution-power' to 0.0 to remove the concentration of mountainous areas.

```
$ fastlem-random-terrain --colormap-json-filename default_color.json --image-size 300:-1 --land-ratio 1.0 --convex-hull-is-always-outlet --erodibility-distribution-power 0.0
```

![terrain](https://github.com/TadaTeruki/fastlem-random-terrain/assets/69315285/c9bc89e3-56d3-48f3-9c82-ea31c146a5b0)

**Comment by setanarut** [comment]
Thanks for the quick response. This is what I wanted but there is a small problem. The output range is not 0-255. (dark image) When I normalize with Auto-level, there is a loss of quality. Is it possible to normalize the image while processing it?

```
./fastlem --image-size 500:500 --land-ratio 1.0 --convex-hull-is-always-outlet --erodibility-distribution-power 0.0
```

![terrain](https://github.com/TadaTeruki/fastlem-random-terrain/assets/36481442/8ce762d7-deb5-43c7-bd49-301cee0925cf)

Red circle indicates loss of quality.

![333](https://github.com/TadaTeruki/fastlem-random-terrain/assets/36481442/a85bfa6a-2b36-4d07-9db4-8654b345a984)

**Comment by setanarut** [comment]
You can also consider the higher bit depth PNG option to get lossless height values (16-bit and 32-bit) thanks

**Comment by setanarut** [comment]
here is detail of `--bound 10000:10000 --image-size 10000:10000`. There are only 15 colors in 10000x10000 image.


![Untitled](https://github.com/TadaTeruki/fastlem-random-terrain/assets/36481442/c17a1cb7-63ca-4543-bdf4-450057ea747d)

**Comment by TadaTeruki** [comment]
> The output range is not 0-255.

Sorry, but this CLI still cannot use relative elevation to the highest point of the terrain.

You can easily solve this by defining colormap yourself like this:

```json:grayscale.json
[
    {
        "color": [0, 0, 0],
        "elevation": 0.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 15.0
    }
]

```

```
$ --image-size 500:500 --land-ratio 1.0 --convex-hull-is-always-outlet --erodibility-distribution-power 0.0 --colormap-json-filename grayscale.json
```

Note that this uses an abusolute height value to define the colormap. You need to adjust it manually for other patterns.

If you need to use relative value to render using current implementation, you need to use colormap like below, which can convert to more accurate elevation by calculating RGB value, and convert it to grayscale using scripts you define.

```json:grayscale.json
[
    {
        "color": [0, 0, 0],
        "elevation": 0.0
    },
    {
        "color": [0, 0, 255],
        "elevation": 10.0
    },
    {
        "color": [0, 255, 255],
        "elevation": 20.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 30.0
    }
]
```

> consider the higher bit depth PNG option

This is worth to try.
I also think this CLI needs to output data not only by PNG, but other format that allows to query more accurate elevations, such as CSV data.

**Comment by TadaTeruki** [comment]
For the latest version (c7fa59a) I added `--output-format` and `--global-max-slope`. now you can output terrain data as csv and limit the slope angle. See `--help` for details.

**Comment by setanarut** [comment]
> If you need to use relative value to render using current implementation, you need to use colormap like below, which can convert to more accurate elevation by calculating RGB value, and convert it to grayscale using scripts you define.

Thanks. When this json file repeats white-black-white-black, I get exactly the pattern I want. Problem solved. But It would be easier to control if the minimum and maximum elevation were fixed within a range. for example [-1, 1].


```json
[
    {
        "color": [0, 0, 0],
        "elevation": 0.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 2.0
    },
    {
        "color": [0, 0, 0],
        "elevation": 4.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 6.0
    },
    {
        "color": [0, 0, 0],
        "elevation": 8.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 10.0
    },
    {
        "color": [0, 0, 0],
        "elevation": 12.0
    },
    {
        "color": [255, 255, 255],
        "elevation": 14.0
    }
]
```

![terrain](https://github.com/TadaTeruki/fastlem-random-terrain/assets/36481442/f4a4e26f-cd7f-44bc-b8ba-e5e3d5b85ec7)


> These terrains are generated by limiting the slope angle.
> fastlem-random-terraindoesn't have this feature yet, but implementing it is not difficult and I think it will be useful for other purposes as well. (I will start now.)

Thanks a lot. I will wait.

**Comment by setanarut** [comment]
> For the latest version ([c7fa59a](https://github.com/TadaTeruki/fastlem-random-terrain/commit/c7fa59af6a3199b3a28c64678b0953c673156227)) I added `--output-format` and `--global-max-slope`. now you can output terrain data as csv and limit the slope angle. See `--help` for details.

Thanks
